let src = cv.imread('imageCanvasInput')
let templ = cv.imread('templateCanvasInput')
let dst = new cv.Mat()
let mask = new cv.Mat()
cv.matchTemplate(src, templ, dst, cv.TM_CCOEFF, mask)
let result = cv.minMaxLoc(dst, mask)
let maxPoint = result.maxLoc
let color = new cv.Scalar(255, 0, 0, 255)
let point = new cv.Point(maxPoint.x + templ.cols, maxPoint.y + templ.rows)
cv.rectangle(src, maxPoint, point, color, 2, cv.LINE_8, 0)
cv.imshow('canvasOutput', src)
src.delete()
dst.delete()
mask.delete()
